FROM loadimpact/k6

ENV SCRIPT tests/test_login.js
ENV Environment dev
ENV STAGE 5m:20,10m:20,5m:0
ENV SCENARIO Test_Example_01
COPY . .
ENTRYPOINT []
CMD ["sh", "-c", "K6_STATSD_ENABLE_TAGS=true k6 run $SCRIPT --stage $STAGE --out statsd  --system-tags scenario= --tag scenario=$SCENARIO"]
